Repository 5ttuki-Curry/OttukiDinning, pull requests merged in 2024-04, with the labels that each got.

#2 [Feat] 임시 수정 #1
  OttukiDinning/ViewController.swift
Labels: Feature

#10 [Fix] Merge를 위한 수정 #6
  OttukiDinning/LogInViewController.swift
  OttukiDinning/Main.storyboard
  OttukiDinning/SignUpViewController.swift
Labels: Fix

#13 [Sion] search page
  OttukiDinning.xcodeproj/project.pbxproj
  OttukiDinning/CollectionViewCell.swift
  OttukiDinning/CollectionViewCell.xib
  OttukiDinning/ListCell.swift
  OttukiDinning/ListCell.xib
  OttukiDinning/SampleData.swift
  OttukiDinning/Sion.storyboard
  OttukiDinning/SionViewController.swift
Labels: Feature

#17 Homedesign에서 Develop 브랜치로 머지
  OttukiDinning.xcodeproj/project.pbxproj
  OttukiDinning.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OttukiDinning.xcodeproj/xcuserdata/t2023-m0056.xcuserdatad/xcschemes/xcschememanagement.plist
  OttukiDinning/Assets.xcassets/NoImage.imageset/Contents.json
  OttukiDinning/Assets.xcassets/NoImage.imageset/image 30.svg
  OttukiDinning/DetailViewController.swift
  OttukiDinning/HomeCollectionViewCell.swift
  OttukiDinning/HomeView.storyboard
  OttukiDinning/HomeViewController.swift
  OttukiDinning/HorizontalViewCell.swift
  OttukiDinning/LogInViewController.swift
  OttukiDinning/NetworkManager.swift
Labels: Feature, Fix, Merge

#20 (dev-sionK) 서치바 및 검색결과 구현 중
  OttukiDinning.xcodeproj/project.pbxproj
  OttukiDinning.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OttukiDinning.xcodeproj/xcshareddata/xcschemes/OttukiDinning.xcscheme
  OttukiDinning/Assets.xcassets/Colors/Contents.json
  OttukiDinning/Assets.xcassets/Colors/HeadTextColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Colors/MainColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Colors/PointColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Colors/PriceColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Colors/ShadowColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Colors/SubTextColor.colorset/Contents.json
  OttukiDinning/Assets.xcassets/Home.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Home.imageset/image 7.svg
  OttukiDinning/Assets.xcassets/HomeEmpty.imageset/Contents.json
  OttukiDinning/Assets.xcassets/HomeEmpty.imageset/image 8.png
  OttukiDinning/Assets.xcassets/KakaoLogIn.imageset/Contents.json
  OttukiDinning/Assets.xcassets/KakaoLogIn.imageset/kakao_login_button.png
  OttukiDinning/Assets.xcassets/MyInfo.imageset/Contents.json
  OttukiDinning/Assets.xcassets/MyInfo.imageset/image 5.svg
  OttukiDinning/Assets.xcassets/Profile.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Profile.imageset/profile.svg
  OttukiDinning/Assets.xcassets/Reservation.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Reservation.imageset/Group 2445.svg
  OttukiDinning/Assets.xcassets/Restaurant.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Restaurant.imageset/image 18.svg
  OttukiDinning/Assets.xcassets/Search.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Search.imageset/image 4.svg
  OttukiDinning/Assets.xcassets/Search2.imageset/Contents.json
  OttukiDinning/Assets.xcassets/Search2.imageset/image 4.svg
  OttukiDinning/Base.lproj/Main.storyboard
  OttukiDinning/CollectionViewCell.swift
  OttukiDinning/CollectionViewCell.xib
  OttukiDinning/DetailView.storyboard
  OttukiDinning/DetailViewController.swift
  OttukiDinning/HomeCollectionViewCell.swift
  OttukiDinning/HomeCollectionViewCell.xib
  OttukiDinning/HomeCollectionViewCellDelegate.swift
  OttukiDinning/HomeView.storyboard
  OttukiDinning/HomeViewController.swift
  OttukiDinning/HorizontalViewCell.swift
  OttukiDinning/HorizontalViewCell.xib
  OttukiDinning/Info.plist
  OttukiDinning/ListCell.swift
  OttukiDinning/ListCell.xib
  OttukiDinning/LogInViewController.swift
  OttukiDinning/Main.storyboard
  OttukiDinning/Models/RestaurantData.swift
  OttukiDinning/NetworkManager.swift
  OttukiDinning/SampleData.swift
  OttukiDinning/SearchBarViewController.swift
  OttukiDinning/SignUpViewController.swift
  OttukiDinning/Sion.storyboard
  OttukiDinning/SionViewController.swift
  OttukiDinning/ViewController.swift
Labels: Feature

#19 [Feat] 예약완료 후 홈화면으로 이동
  OttukiDinning.xcodeproj/project.pbxproj
  OttukiDinning/DetailPage.storyboard
  OttukiDinning/DetailPageController.swift
  OttukiDinning/DetailViewController.swift
  OttukiDinning/LogInViewController.swift
Labels: Feature

#24 (Dev sion k) 서치바 오류 수정
  OttukiDinning/CollectionViewCell.swift
  OttukiDinning/Info.plist
  OttukiDinning/ListCell.swift
  OttukiDinning/Sion.storyboard
  OttukiDinning/SionViewController.swift
Labels: Fix

#26 [Design] 상세화면 AutoLayout 문제 해결 및 View이동 추가 #5
  OttukiDinning.xcodeproj/project.pbxproj
  OttukiDinning/ButtonManager.swift
  OttukiDinning/DetailViewController.swift
  OttukiDinning/HomeViewController.swift
  OttukiDinning/SionViewController.swift
Labels: Feature, Design

#31 검색화면에서 셀 선택시 상세화면으로 이동해서 예약이 가능하도록 기능 구현 후 머지
  OttukiDinning/Controllers/DetailPageController.swift
  OttukiDinning/Controllers/LogInViewController.swift
  OttukiDinning/Controllers/SionViewController.swift
  OttukiDinning/Models/ButtonManager.swift
Labels: Feature, Fix, Merge
